In [1]:
import numpy as np
print('numpy version:', np.__version__)

import matplotlib as mpl
print('matplotlib version:', mpl.__version__)
import matplotlib.pyplot as plt


numpy version: 1.23.5
matplotlib version: 3.6.2


In [2]:
x1 = 2.3
x2 = 3.2
np.matrix([[x1],[x2]])

matrix([[2.3],
        [3.2]])

In [3]:
np.matrix('1. 1.; 1. 1.; 1. 1.')

matrix([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
np.matrix('0.; 0.; 0.') # 3 rows by 1 column

matrix([[0.],
        [0.],
        [0.]])

In [5]:
np.matrix('0. 0. 0.') # 1 row by 3 column

matrix([[0., 0., 0.]])