In [1]:
import numpy as np
print('numpy version:', np.__version__)

import matplotlib as mpl
print('matplotlib version:', mpl.__version__)
import matplotlib.pyplot as plt


numpy version: 1.23.5
matplotlib version: 3.6.2


In [2]:
x1 = 2.3
x2 = 3.2
np.matrix([[x1],[x2]])

matrix([[2.3],
        [3.2]])

In [3]:
np.matrix('1. 1.; 1. 1.; 1. 1.')

matrix([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
np.matrix('0.; 0.; 0.') # 3 rows by 1 column

matrix([[0.],
        [0.],
        [0.]])

In [5]:
np.matrix('0. 0. 0.') # 1 row by 3 column

matrix([[0., 0., 0.]])

In [17]:
s0 = np.array([0, 0]).reshape(-1, 1)
wss = np.array([[-1, 0], [0, 1]])
wsx = np.array([[1, 0], [0, 1]])

In [13]:
x1 = np.array([[1, 0], [1, 0]]).T
x2 = np.array([[1, 0], [0, 1], [0, 1]]).T
x3 = np.array([[0, 1], [1, 0], [1, 0]]).T

For x1

In [21]:
s1 = (wss @ s0) + (wsx @ x1[:, 0].reshape(-1, 1))
s1

array([[1],
       [0]])

In [23]:
s2 = (wss @ s1) + (wsx @ x1[:, 1].reshape(-1, 1))
s2

array([[0],
       [0]])

For x2

In [27]:
def relu(x):
    return np.where(x < 0, 0, x)

In [29]:
s1 = (wss @ s0) + (wsx @ x2[:, 0].reshape(-1, 1))
s1

array([[1],
       [0]])

In [31]:
s1 = relu(s1)
s1

array([[1],
       [0]])

In [32]:
s2 = (wss @ s1) + (wsx @ x2[:, 1].reshape(-1, 1))
s2

array([[-1],
       [ 1]])

In [33]:
s2 = relu(s2)
s2

array([[0],
       [1]])

In [34]:
s3 = (wss @ s2) + (wsx @ x2[:, 2].reshape(-1, 1))
s3

array([[0],
       [2]])

In [36]:
s3 = relu(s3)
s3

array([[0],
       [2]])

In [37]:
s = s0.copy()
for i in range(x3.shape[1]):
    print(f'======= Step {i+1} =========')
    a = x3[:, i].reshape(-1, 1)
    s = (wss @ s) + (wsx @ a)
    print(s)
    s = relu(s)
    print(s)

======= Step 1 =========
[[0]
 [1]]
[[0]
 [1]]
======= Step 2 =========
[[1]
 [1]]
[[1]
 [1]]
======= Step 3 =========
[[0]
 [1]]
[[0]
 [1]]
