In [1]:
import numpy as np
print('numpy version:', np.__version__)

import matplotlib as mpl
print('matplotlib version:', mpl.__version__)
import matplotlib.pyplot as plt


numpy version: 1.23.5
matplotlib version: 3.6.2


In [2]:
mus = np.array([-3., 2.])
sigmas_sq = np.array([4., 4.])
weights = np.array([.5, .5])
x = np.array([.2, -.9, -1, 1.2, 1.8])

In [6]:
x.reshape(-1, 1) - mus

array([[ 3.2, -1.8],
       [ 2.1, -2.9],
       [ 2. , -3. ],
       [ 4.2, -0.8],
       [ 4.8, -0.2]])

In [10]:
mu = -3.
sigma_sq = 4.
weight = .5

In [18]:
x-mu

array([3.2, 2.1, 2. , 4.2, 4.8])

In [12]:
(x - mu)**2

array([10.24,  4.41,  4.  , 17.64, 23.04])

In [25]:
c1_posterior = np.exp(-((x-mu)**2)/(2*sigma_sq))/((2*np.pi*sigma_sq)**0.5)*weight
c1_posterior

array([0.02773021, 0.05747054, 0.06049268, 0.0109959 , 0.00559863])

In [23]:
mu2 = 2.
sigma_sq2 = 4.
weight2 = .5

In [26]:
c2_posterior = np.exp(-((x-mu2)**2)/(2*sigma_sq2))/((2*np.pi*sigma_sq2)**0.5)*weight2
c2_posterior

array([0.06652131, 0.03485764, 0.0323794 , 0.09206754, 0.09923814])

In [28]:
c1_posterior / (c1_posterior+c2_posterior)

array([0.29421497, 0.62245933, 0.65135486, 0.10669059, 0.05340333])

In [8]:
def compute_posterior(X, weights, mus, sigmas_sq):
    X = X.reshape(-1, 1)
    deltas = X - mus
    return weights * 1 / ((2 * np.pi * sigmas_sq)**0.5) * np.exp(-(deltas ** 2)/(2 * sigmas_sq))

In [13]:
tmp = compute_posterior(x, weights=weights, mus=mus, sigmas_sq=sigmas_sq)
tmp

array([[0.02773021, 0.06652131],
       [0.05747054, 0.03485764],
       [0.06049268, 0.0323794 ],
       [0.0109959 , 0.09206754],
       [0.00559863, 0.09923814]])

In [30]:
tmp.sum(axis=1)

array([0.09425152, 0.09232818, 0.09287208, 0.10306343, 0.10483677])

In [33]:
posteriors = tmp / tmp.sum(axis=1).reshape(-1, 1)
posteriors

array([[0.29421497, 0.70578503],
       [0.62245933, 0.37754067],
       [0.65135486, 0.34864514],
       [0.10669059, 0.89330941],
       [0.05340333, 0.94659667]])

In [35]:
n_hat1 = posteriors[:, 0].sum()
n_hat1

1.7281230917763732

In [37]:
p_hat1 = n_hat1 / x.shape[0]
p_hat1

0.34562461835527464

In [39]:
mu_hat1 = (posteriors[:, 0] * x).sum() / n_hat1
mu_hat1

-0.5373289474340418

In [40]:
sigma_sq_hat1 = (posteriors[:, 0] * (x - mu_hat1)**2).sum() / n_hat1
sigma_sq_hat1

0.5757859076870627